export {default as Blog} from './blog/Blog'
export {default as GetStarted} from './getstarted/GetStarted'
export {default as Footer} from './footer/Footer'
export {default as Header} from './header/Header'
export {default as Possibility} from './possibility/Possibility'
export {default as Functionality} from './functionality/Functionality'
export {default as Topvote} from './topvote/Topvote'
export {default as Ranking} from './rankings/Ranking'